import pandas as pd
import numpy as np
from pathlib import Path

def generate_report(csv_path: str, output_path: str):
    df = pd.read_csv(csv_path)
    if df.empty:
        print("CSV is empty")
        return

    # Sort by exit time
    df['exit_time'] = pd.to_datetime(df['exit_time'])
    df['entry_time'] = pd.to_datetime(df['entry_time'])
    df = df.sort_values('exit_time')

    # Metrics
    total_pnl = df['pnl'].sum()
    win_rate = (df['pnl'] > 0).mean()
    avg_pnl = df['pnl'].mean()
    total_fees = df['fees'].sum()
    
    # Cumulative PnL Curve
    df['cumulative_pnl'] = df['pnl'].cumsum()
    
    # Detailed Analysis
    gross_profit = df[df['pnl'] > 0]['pnl'].sum()
    gross_loss = abs(df[df['pnl'] < 0]['pnl'].sum())
    profit_factor = gross_profit / gross_loss if gross_loss != 0 else float('inf')
    
    # Drawdown
    cum_max = df['cumulative_pnl'].cummax()
    drawdown = df['cumulative_pnl'] - cum_max
    max_drawdown = drawdown.min()
    
    # Ratios
    # Assuming initial capital from config or default 100k
    initial_capital = 100000.0 
    daily_returns = df.groupby(df['exit_time'].dt.date)['pnl'].sum() / initial_capital
    sharpe = (daily_returns.mean() / daily_returns.std() * np.sqrt(252)) if len(daily_returns) > 1 and daily_returns.std() != 0 else 0

    # Best and Worst
    best_trade = df.loc[df['pnl'].idxmax()]
    worst_trade = df.loc[df['pnl'].idxmin()]
    
    # Duration
    df['duration'] = df['exit_time'] - df['entry_time']
    avg_duration = df['duration'].mean()

    # Asset Stats
    asset_stats = df.groupby('symbol_long').agg({
        'pnl': ['sum', 'count', 'mean'],
        'fees': 'sum'
    }).sort_values(('pnl', 'sum'), ascending=False)
    asset_stats.columns = ['Total PnL', 'Trades', 'Avg PnL', 'Total Fees']

    # Markdown Construction
    report = f"""# 💎 Trading Performance Analytics

## ⚡ Performance Summary
| Metric | Value | Breakdown |
| :--- | :--- | :--- |
| **Net Profit** | **${total_pnl:,.2f}** | After ${total_fees:,.2f} in fees |
| **Return on Capital** | **{total_pnl/initial_capital:.2%}$** | Based on ${initial_capital:,.0f} |
| **Win Rate** | **{win_rate:.2%}** | {sum(df['pnl'] > 0)} Win / {sum(df['pnl'] <= 0)} Loss |
| **Profit Factor** | **{profit_factor:.2f}** | Gross Profit: ${gross_profit:,.2f} |
| **Max Drawdown** | **${max_drawdown:,.2f}** | Peak-to-trough decline |
| **Sharpe Ratio (Annual)** | **{sharpe:.2f}** | Risk-adjusted return |

## 📉 Cumulative Profit Curve
| Sequence | Trade | Exit Time | PnL | Running Total |
| :--- | :--- | :--- | :--- | :--- |
"""
    
    for i, row in df.iterrows():
        report += f"| {i+1} | {row['symbol_long']}/{row['symbol_short']} | {row['exit_time'].strftime('%Y-%m-%d')} | ${row['pnl']:,.2f} | **${row['cumulative_pnl']:,.2f}** |\n"

    report += f"""
## 🏆 Alpha Insights
> **Key Observation**: The strategy showed its strongest performance in trades involving **{best_trade['symbol_long']}**.
> The average holding time of **{avg_duration}** suggests a medium-term mean reversion profile.

### 🌟 Top 5 Performing Assets
{asset_stats.head(5).to_markdown()}

## 🛠 Raw Performance Data (Last 50 Trades)
{df[['symbol_long', 'symbol_short', 'entry_time', 'exit_time', 'pnl', 'fees']].tail(50).to_markdown(index=False)}

---
*Report generated by Antigravity AI Engine*
*Timestamp: {pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S UTC")}*
"""

    with open(output_path, 'w') as f:
        f.write(report)
    print(f"Comprehensive report saved to {output_path}")

if __name__ == "__main__":
    import sys
    csv = sys.argv[1] if len(sys.argv) > 1 else "reports/backtest_rolling_1h_f60_t7.csv"
    generate_report(csv, "reports/TRADE_REPORT.md")
